### ISSUE TITLE
APPName o AppName

### ISSUE THREAD

**Issue by zeroidentidad** [gophers-latam/minimalchi#1]
Se declara como APPName pero se comenta como AppName
A que se debe?

**Comment by areyes-bsale** [comment]
> Se declara como APPName pero se comenta como AppName
> A que se debe?

Hola. Gracias por avisar. Obviamente es un typo. PRs son más que bienvenidos😄

**Comment by jackgris** [comment]
Creo que hace comentario te referias @zeroidentidad, ahi envie un pull request, decime si era a otra parte del code.

**Comment by jackgris** [comment]
Ah, y no habia visto que estaba el mismo codigo en el README

**Comment by profe-ajedrez** [comment]
worked on https://github.com/gophers-latam/minimalchi/pull/3
